package com.mycelbot.worldbase.engine.systems;

import com.mycelbot.worldbase.config.GameConfig;
import com.mycelbot.worldbase.engine.IslandInfo;
import com.mycelbot.worldbase.engine.SingleIsland;
import com.mycelbot.worldbase.engine.TileType;
import com.mycelbot.worldbase.engine.components.AppearanceComponent;
import com.mycelbot.worldbase.engine.components.PositionComponent;
import com.mycelbot.worldbase.engine.components.TileComponent;
import com.mycelbot.worldbase.engine.components.ZComponent;
import com.mycelbot.worldbase.engine.ecs.Entity;
import com.mycelbot.worldbase.engine.ecs.EntityManager;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import java.util.Random;

/**
 * Generates a world of water with multiple noise-shaped islands at
 * non-overlapping positions.
 * <p>
 * Two render layers:
 * <ul>
 *   <li>Z=0 — full width×height water grid (background)</li>
 *   <li>Z=1 — grass island tiles from noise + radial falloff</li>
 * </ul>
 * <p>
 * Each island is generated by {@link SingleIslandGenerator}, already
 * smoothed (perpendicular-edge rule) and trimmed to its bounding box.
 * Islands are placed so they do not touch (minimum gap of 3 tiles).
 * After placement, a connected-component pass removes any fragments
 * below the threshold.
 * <p>
 * Surviving island metadata is exposed via {@link #getIslands()}.
 * All tunable parameters are taken from GameConfig.
 */
public class IslandWorldGenerator extends WorldGenerator {

    private static final int MIN_ISLAND_TILES = 5;
    private static final int ISLAND_GAP = 4;
    private static final int ISLAND_COUNT = 2;

    private final Random rng;

    private final double frequency;
    private final int octaves;
    private final double radiusFraction;
    private final double threshold;

    private List<IslandInfo> islands;
    private long nextSeed = System.currentTimeMillis();

    public IslandWorldGenerator() {
        this(0.04, 4, 0.45, 0.0);
    }

    public IslandWorldGenerator(GameConfig config) {
        this(
            config.getNoiseFrequency(),
            config.getNoiseOctaves(),
            config.getIslandRadiusFraction(),
            config.getIslandThreshold()
        );
    }

    public IslandWorldGenerator(double frequency, int octaves,
                                 double radiusFraction, double threshold) {
        this.rng = new Random();
        this.frequency = frequency;
        this.octaves = octaves;
        this.radiusFraction = radiusFraction;
        this.threshold = threshold;
    }

    @Override
    public void generate(EntityManager em, int width, int height) {
        int[] waterVariants = TileType.WATER.getInteriorVariants();

        // Layer 0: full water grid
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                int waterSprite = waterVariants[rng.nextInt(waterVariants.length)];
                var e = em.createEntity();
                em.addComponent(e, new PositionComponent(x, y));
                em.addComponent(e, new ZComponent(0));
                em.addComponent(e, new TileComponent(TileType.WATER));
                em.addComponent(e, new AppearanceComponent(waterSprite));
            }
        }

        // Generate and place islands
        SingleIslandGenerator singleGen = new SingleIslandGenerator(
            frequency, octaves, radiusFraction, threshold);

        int genSize = Math.min(width, height);
        List<PlacedIsland> placed = new ArrayList<>();

        for (int i = 0; i < ISLAND_COUNT; i++) {
            SingleIsland island = singleGen.generate(nextSeed++, genSize);
            if (island.tileCount == 0) continue; // skip empty

            int[] pos;
            if (i == 0) {
                // First island: centre it
                pos = new int[]{
                    (width - island.width) / 2,
                    (height - island.height) / 2
                };
            } else {
                pos = findPlacement(width, height, placed, island);
            }

            if (pos == null) {
                // Couldn't fit this island — skip
                continue;
            }

            placeIsland(em, island, pos[0], pos[1]);
            placed.add(new PlacedIsland(island, pos[0], pos[1]));
        }

        // Lay grass entities and record island info
        this.islands = new ArrayList<>();
        for (PlacedIsland pi : placed) {
            int sumX = 0, sumY = 0, count = 0;
            for (int x = 0; x < pi.island.width; x++) {
                for (int y = 0; y < pi.island.height; y++) {
                    if (pi.island.tiles[x][y]) {
                        sumX += pi.ox + x;
                        sumY += pi.oy + y;
                        count++;
                    }
                }
            }
            islands.add(new IslandInfo(
                islands.size(),
                count,
                (float) sumX / count,
                (float) sumY / count
            ));
        }

        // Clean up any stray fragments
        removeSmallIslands(em, width, height);
    }

    // ──────────────────────────────────────────────
    //  Island placement
    // ──────────────────────────────────────────────

    private static class PlacedIsland {
        final SingleIsland island;
        final int ox, oy;
        PlacedIsland(SingleIsland island, int ox, int oy) {
            this.island = island;
            this.ox = ox;
            this.oy = oy;
        }
    }

    /**
     * Try to find a non-overlapping position for {@code island} that
     * keeps {@value #ISLAND_GAP} tiles of water between it and all
     * already-placed islands.
     */
    private int[] findPlacement(int worldW, int worldH,
                                List<PlacedIsland> placed,
                                SingleIsland island) {
        int gap = ISLAND_GAP;
        int iw = island.width;
        int ih = island.height;

        // Try a handful of candidate positions
        int[][] candidates = {
            {0, 0},
            {worldW - iw, 0},
            {0, worldH - ih},
            {worldW - iw, worldH - ih},
            {worldW / 4, worldH / 4},
            {worldW / 2 - iw / 2, worldH / 4},
            {worldW / 4, worldH / 2 - ih / 2},
            {worldW / 2 - iw / 2, worldH / 2 - ih / 2},
        };

        for (int[] cand : candidates) {
            int cx = cand[0];
            int cy = cand[1];
            if (cx < 0 || cy < 0 || cx + iw > worldW || cy + ih > worldH) continue;

            boolean ok = true;
            for (PlacedIsland p : placed) {
                if (overlaps(cx, cy, iw, ih,
                             p.ox, p.oy, p.island.width, p.island.height, gap)) {
                    ok = false;
                    break;
                }
            }
            if (ok) return new int[]{cx, cy};
        }

        return null;
    }

    /** Check if two rectangles overlap when each has a gap margin. */
    private static boolean overlaps(int x1, int y1, int w1, int h1,
                                    int x2, int y2, int w2, int h2,
                                    int gap) {
        boolean separate = x1 + w1 + gap <= x2
                        || x1 >= x2 + w2 + gap
                        || y1 + h1 + gap <= y2
                        || y1 >= y2 + h2 + gap;
        return !separate;
    }

    // ──────────────────────────────────────────────
    //  Tile entity creation
    // ──────────────────────────────────────────────

    /** Place an island's grass tiles into the world at (ox, oy). */
    private void placeIsland(EntityManager em, SingleIsland island, int ox, int oy) {
        int[] grassVariants = TileType.GRASS.getInteriorVariants();
        for (int x = 0; x < island.width; x++) {
            for (int y = 0; y < island.height; y++) {
                if (!island.tiles[x][y]) continue;
                int grassSprite = grassVariants[rng.nextInt(grassVariants.length)];
                var e = em.createEntity();
                em.addComponent(e, new PositionComponent(ox + x, oy + y));
                em.addComponent(e, new ZComponent(1));
                em.addComponent(e, new TileComponent(TileType.GRASS));
                em.addComponent(e, new AppearanceComponent(grassSprite));
            }
        }
    }

    // ──────────────────────────────────────────────
    //  Small-island cleanup
    // ──────────────────────────────────────────────

    /**
     * Remove any grass islands (connected components via 4-direction BFS)
     * with fewer than {@value #MIN_ISLAND_TILES} tiles. Rebuilds the island
     * list afterwards.
     */
    public void removeSmallIslands(EntityManager em, int width, int height) {
        boolean[][] isGrass = buildGrassGrid(em, width, height);
        boolean[][] visited = new boolean[width][height];
        List<IslandInfo> surviving = new ArrayList<>();
        int islandId = 0;

        int[] dx = { 0,  0, -1,  1};
        int[] dy = { 1, -1,  0,  0};

        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                if (!isGrass[x][y] || visited[x][y]) continue;

                List<int[]> componentTiles = new ArrayList<>();
                Queue<int[]> queue = new ArrayDeque<>();
                queue.add(new int[]{x, y});
                visited[x][y] = true;

                while (!queue.isEmpty()) {
                    int[] tile = queue.poll();
                    componentTiles.add(tile);
                    for (int d = 0; d < 4; d++) {
                        int nx = tile[0] + dx[d];
                        int ny = tile[1] + dy[d];
                        if (nx >= 0 && nx < width && ny >= 0 && ny < height
                                && isGrass[nx][ny] && !visited[nx][ny]) {
                            visited[nx][ny] = true;
                            queue.add(new int[]{nx, ny});
                        }
                    }
                }

                int size = componentTiles.size();
                if (size < MIN_ISLAND_TILES) {
                    for (int[] tile : componentTiles) {
                        for (Entity entity : em.getAllEntitiesWith(
                                PositionComponent.class, TileComponent.class)) {
                            TileComponent tc = em.getComponent(entity, TileComponent.class);
                            if (tc.type != TileType.GRASS) continue;
                            PositionComponent pos = em.getComponent(entity, PositionComponent.class);
                            if (pos.x == tile[0] && pos.y == tile[1]) {
                                isGrass[tile[0]][tile[1]] = false;
                                em.destroyEntity(entity);
                                break;
                            }
                        }
                    }
                } else {
                    float sumX = 0, sumY = 0;
                    for (int[] tile : componentTiles) {
                        sumX += tile[0];
                        sumY += tile[1];
                    }
                    surviving.add(new IslandInfo(
                        islandId++,
                        size,
                        sumX / size,
                        sumY / size
                    ));
                }
            }
        }

        this.islands = surviving;
    }

    @Override
    public List<IslandInfo> getIslands() {
        return islands != null ? islands : List.of();
    }

    private boolean[][] buildGrassGrid(EntityManager em, int width, int height) {
        boolean[][] grid = new boolean[width][height];
        for (Entity entity : em.getAllEntitiesWith(
                PositionComponent.class, TileComponent.class)) {
            TileComponent tc = em.getComponent(entity, TileComponent.class);
            if (tc.type == TileType.GRASS) {
                PositionComponent pos = em.getComponent(entity, PositionComponent.class);
                grid[pos.x][pos.y] = true;
            }
        }
        return grid;
    }
}
